from ubuntu:12.04
maintainer Evan Hazlett <ejhazlett@gmail.com>
run apt-get update
run DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
run apt-get install -y python-dev python-setuptools libxml2-dev libxslt-dev
run easy_install pip
run pip install uwsgi
