#!/bin/bash
if [ ! -f /data/minecraft_server.jar  ]
then
    curl -sSL https://launcher.mojang.com/v1/objects/f1a0073671057f01aa843443fef34330281333ce/server.jar -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt  ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui
